name: Android Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          tags: true
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Extract versionName
        id: version
        run: |
          VERSION_NAME=$(grep 'versionName =' app/build.gradle.kts | head -1 | sed -E 's/.*"(.+)".*/\1/')
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Generate Release Notes
        id: notes
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || true)
          echo "Last tag: $LAST_TAG"
          if [ -n "$LAST_TAG" ]; then
              RELEASE_NOTES=$(git log ${LAST_TAG}..HEAD --pretty=format:"- %s")
          else
              RELEASE_NOTES=$(git log --pretty=format:"- %s")
          fi
          if [ -z "$RELEASE_NOTES" ]; then
              echo "No commits found since the last tag. Aborting release."
              exit 1
          fi
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_NOTES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "$RELEASE_NOTES"

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release.keystore
        shell: bash

      - name: Build Signed Release APK
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_FILE: ${{ github.workspace }}/release.keystore
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: List APKs
        run: ls -R app/build/outputs/apk/release/

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          commit: main
          tag: ${{ env.VERSION_NAME }}
          name: Release ${{ env.VERSION_NAME }}
          body: ${{ env.RELEASE_NOTES }}
          artifacts: app/build/outputs/apk/release/play-on-dlna-${{ env.VERSION_NAME }}.apk
          draft: false
          prerelease: false
